Repository linz/geostore, pull requests merged in 2020-12, with the labels that each got.

#61 ci: wait if another CI AWS stack already exists
  .github/workflows/ci.yml
Labels: automerge

#104 revert: "ci: wait if another CI AWS stack already exists"
  .github/workflows/ci.yml
Labels: automerge

#106 ci: Wait for stack teardown before deploying
  .github/workflows/ci.yml
  .github/workflows/wait-for-stack-teardown.bash
Labels: automerge

#110 ci: Cache pip downloads
  .github/workflows/ci.yml
Labels: automerge

#108 ci: Use specific Ubuntu version for pipelines
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  README.md
Labels: automerge

#99 Create dataset instances per test
  backend/tests/conftest.py
  backend/tests/test_datasets_endpoint.py
  backend/tests/utils.py
Labels: automerge

#101 docs: Document how to handle poetry.lock
  README.md
Labels: automerge

#113 refactor(infra): more splitting of AWS stacks
  .github/workflows/ci.yml
  infra/app.py
  infra/datalake/api_stack.py
  infra/datalake/storage_stack.py
  infra/tests/test_stack.py
Labels: automerge

#135 ci: use CI AWS account for CI
  .github/workflows/ci.yml
Labels: automerge

#127 test: Pull boto client creation into functions
  infra/tests/__init__.py
  infra/tests/conftest.py
  infra/tests/test_lambda_functions.py
  infra/tests/test_storage_bucket.py
Labels: automerge

#136 ci: re-enable nonprod AWS account deployment (closes #66)
  .github/workflows/ci.yml
Labels: automerge

#137 feat: Upgrade packages
  package-lock.json
  package.json
  poetry.lock
Labels: automerge, dependencies

#132 refactor: Pull CDK app into main directory
  .dockerignore
  .github/workflows/ci.yml
  .gitignore
  CODING.md
  README.md
  app.py
  backend/processing/check_files_checksums/Dockerfile
  backend/processing/check_flat_directory_structure/Dockerfile
  cdk.json
  datalake/__init__.py
  datalake/api_stack.py
  datalake/networking_stack.py
  datalake/processing_stack.py
  datalake/storage_stack.py
  infra/.gitignore
  infra/datalake/__init__.py
  tests/__init__.py
  tests/conftest.py
  tests/test_lambda_functions.py
  tests/test_sample.py
  tests/test_storage_bucket.py
Labels: automerge

#139 feat: Install Node.js packages without changing lock file
  reset-dev-env.bash
Labels: dependencies

#154 fix: Include boto3 dependency for metadata validation
  datalake/backend/processing/check_stac_metadata/Dockerfile
  poetry.lock
  pyproject.toml
Labels: automerge

#151 fix(infra): run 'check_stac_metadata' test first in dataset validation
  datalake/processing_stack.py
Labels: automerge

#159 fix: Remove deploy job dependencies
  .github/workflows/deploy.yml
Labels: automerge

#156 feat: More any functions
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/utils.py
Labels: automerge

#158 feat: Install only production dependencies in Docker container
  .github/workflows/test.yml
  datalake/backend/processing/check_stac_metadata/Dockerfile
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
Labels: automerge
