Repository linz/geostore, pull requests merged in 2021-06, with the labels that each got.

#762 fix: Group boolean operators properly
  .github/workflows/deploy.yml
Labels: automerge

#763 fix: Bootstrap CDK before deploying
  .github/workflows/deploy.yml
Labels: automerge

#764 feat: Use strict CDK deployment option
  .github/workflows/test.yml
Labels: automerge

#766 chore: Bump Poetry installer signature
  backend/Dockerfile
Labels: automerge, bug

#768 feat: Run deployment when pushing release tags
  .github/workflows/deploy.yml
Labels: automerge

#767 refactor: Reverse role assumption for S3 copy prep
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/update.py
  backend/step_function.py
  tests/test_api_endpoint_handler.py
  tests/test_check_stac_metadata.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#771 fix: Use LINZ-specific bucket names
  backend/resources.py
Labels: automerge

#772 tests: Avoid intermittent coverage reduction
  pyproject.toml
  tests/aws_utils.py
  tests/test_processing_stack.py
Labels: automerge, bug

#779 chore: Bump Poetry installer hash
  backend/Dockerfile
Labels: automerge

#783 refactor: Reverse role assumption for S3 copy prep
  backend/aws_response.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/task.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/import_asset_file/task.py
  backend/import_dataset/task.py
  backend/import_dataset_file.py
  backend/import_metadata_file/task.py
  backend/import_status/get.py
  backend/parameter_store.py
  backend/populate_catalog/task.py
  backend/pystac_io_methods.py
  backend/step_function.py
  backend/update_dataset_catalog/task.py
  poetry.lock
  pyproject.toml
  tests/aws_utils.py
  tests/test_check_files_checksums.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_import_dataset_file.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge

#786 fix: Fix a bug with overriden pystac collection write method
  backend/populate_catalog/task.py
  tests/test_populate_catalog.py
Labels: automerge

#795 fix: Add force flag to bootstrap on upgrade to allow copy of prod
  .github/workflows/prod-upgrade-deploy-test.yml
Labels: automerge

#800 fix: Add changeset name to avoid parallel cdk deployment errors
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  .github/workflows/test.yml
Labels: automerge

#790 Update root catalog description and title
  backend/populate_catalog/task.py
Labels: automerge

#801 Revert "fix: Add force flag to bootstrap on upgrade to allow copy of …
  .github/workflows/prod-upgrade-deploy-test.yml
Labels: automerge

#802 refactor: Remove cdk bootstrapping command from pipelines
  .github/workflows/cdk-bootstrap.yml
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  .github/workflows/test.yml
Labels: automerge

#798 docs: Fix pyenv install command
  README.md
  reset-dev-env.bash
Labels: automerge, documentation

#804 refactor: Reverse role assumption for S3 copy prep
  infrastructure/constructs/api.py
  infrastructure/constructs/import_file_function.py
  tests/aws_utils.py
Labels: automerge

#805 tests: Make sure to check against all expected items
  tests/test_check_stac_metadata.py
Labels: automerge

#806 refactor: Reverse role assumption for S3 copy prep
  backend/check_files_checksums/task.py
  backend/datasets/delete.py
  backend/update_dataset_catalog/task.py
  tests/test_check_files_checksums.py
Labels: automerge

#807 refactor: Remove unnecessary test classes
  tests/test_networking_stack.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge

#808 refactor: Import built in properties directly
  backend/dataset_versions/create.py
  backend/import_status/get.py
  backend/log.py
  backend/step_function.py
  infrastructure/constructs/removal_policy.py
  tests/aws_utils.py
  tests/conftest.py
  tests/general_generators.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset_file.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
  tests/test_step_function_logging.py
Labels: automerge

#811 refactor: Simplify type checking imports
  backend/import_asset_file/task.py
  backend/import_dataset/task.py
  backend/import_dataset_file.py
  backend/step_function.py
  backend/update_dataset_catalog/task.py
Labels: automerge

#809 tests: Verify branch coverage
  README.md
  pyproject.toml
  tests/aws_utils.py
Labels: automerge

#813 feat: Log dataset file import result
  backend/import_dataset_file.py
  tests/test_import_dataset_file.py
Labels: automerge

#812 refactor: Reverse role assumption for S3 copy prep
  backend/datasets_model.py
  backend/import_dataset/task.py
  backend/step_function.py
  backend/sts.py
  tests/conftest.py
  tests/test_import_dataset.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
  tests/test_step_function_logging.py
  tests/test_upload_status.py
Labels: automerge

#815 tests: Add stub packages
  poetry.lock
  pyproject.toml
Labels: automerge

#816 refactor: Simplify missing import silencing
  backend/api_responses.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/stac_validators.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/update.py
  backend/import_dataset/task.py
  backend/import_status/get.py
  backend/populate_catalog/task.py
  backend/update_dataset_catalog/task.py
  backend/upload_status/task.py
  backend/validation_summary/task.py
  setup.cfg
  tests/aws_utils.py
  tests/stac_generators.py
  tests/test_api_endpoint_handler.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_content_iterator.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_logging.py
  tests/test_populate_catalog.py
  tests/test_processing_stack.py
  tests/test_update_dataset_catalog.py
  tests/test_upload_status.py
Labels: automerge

#817 docs: Explain how to set up dev env script crontab entry
  README.md
Labels: automerge

#818 feat: Run CodeQL analysis on all pushes
  .github/workflows/codeql-analysis.yml
Labels: automerge

#781 feat: Reverse role assumption for S3 copy
  USAGE.md
  backend/check_files_checksums/task.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/task.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/update.py
  backend/import_asset_file/task.py
  backend/import_dataset/task.py
  backend/import_dataset_file.py
  backend/import_metadata_file/task.py
  backend/import_status/get.py
  backend/resources.py
  backend/s3.py
  backend/step_function.py
  backend/step_function_keys.py
  backend/update_dataset_catalog/task.py
  backend/upload_status/task.py
  backend/validation_summary/task.py
  infrastructure/application_stack.py
  infrastructure/constructs/api.py
  infrastructure/constructs/import_file_function.py
  infrastructure/constructs/processing.py
  infrastructure/constructs/staging.py
  infrastructure/constructs/sts_policy.py
  poetry.lock
  pyproject.toml
  tests/aws_utils.py
  tests/general_generators.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_content_iterator.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_asset_file.py
  tests/test_import_dataset.py
  tests/test_import_dataset_file.py
  tests/test_import_dataset_logging.py
  tests/test_import_metadata_file.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
  tests/test_step_function_logging.py
  tests/test_update_dataset_catalog.py
  tests/test_upload_status.py
  tests/test_upload_status_logging.py
  tests/test_validation_summary.py
  tests/test_validation_summary_logging.py
Labels: automerge, enhancement

#822 fix: Allow staging users role assumption only by main principal
  infrastructure/constructs/processing.py
Labels: automerge

#828 docs: Add lgtm.com badges
  README.md
Labels: automerge

#842 chore: update mypy packages
  poetry.lock
  tests/aws_utils.py
Labels: automerge

#837 feat: add access for OpenTopography.org
  README.md
  cdk.json
  infrastructure/application_stack.py
  infrastructure/constructs/opentopo.py
Labels: automerge

#846 fix: Move staging back to top level
  infrastructure/application_stack.py
  infrastructure/constructs/processing.py
Labels: automerge
