Repository linz/geostore, pull requests merged in 2021-03, with the labels that each got.

#306 Update coding documentation
  CODING.md
  README.md
Labels: automerge, documentation

#313 fix: Use new stac assets property name
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_check_stac_metadata_logging.py
  datalake/backend/tests/test_processing_stack.py
Labels: automerge, bug

#320 docs: usage for staging bucket permissions
  USAGE.md
Labels: automerge

#308 feat: Import dataset task
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  CODING.md
  app.py
  backend/check_files_checksums/task.py
  backend/check_stac_metadata/task.py
  backend/dataset_versions/create.py
  backend/import_dataset/__init__.py
  backend/import_dataset/task.py
  backend/model.py
  backend/utils.py
  infrastructure/api_stack.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
  response.json
  tests/conftest.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_lambda_functions.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
  tests/utils.py
Labels: automerge

#335 refactor: Inline constant field values
  backend/model.py
  infrastructure/storage_stack.py
Labels: automerge, python

#343 fix: Mark test as infrastructure
  tests/test_import_dataset_logging.py
Labels: automerge

#344 refactor: simplify check STAC metadata
  backend/check_stac_metadata/task.py
  backend/utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
Labels: automerge, python

#310 docs: Document import restrictions
  USAGE.md
Labels: automerge, documentation

#358 chore: Upgrade Python packages
  poetry.lock
Labels: automerge, dependencies, python

#361 feat: Ignore third party package directories for CodeQL scan
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: automerge, enabler story, security

#350 refactor: Pull apart shared code
  CODING.md
  app.py
  backend/api_responses.py
  backend/check_files_checksums/task.py
  backend/check_stac_metadata/task.py
  backend/content_iterator/task.py
  backend/dataset.py
  backend/dataset_model.py
  backend/dataset_versions/create.py
  backend/dataset_versions/entrypoint.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/entrypoint.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  backend/environment.py
  backend/import_dataset/task.py
  backend/log.py
  backend/parameter_store.py
  backend/processing_assets_model.py
  backend/resources.py
  backend/utils.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
  tests/aws_utils.py
  tests/conftest.py
  tests/general_generators.py
  tests/stac_generators.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
  tests/test_content_iterator.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge, python

#362 refactor: Use "should_" test name prefix
  pyproject.toml
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
  tests/test_content_iterator.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge, python

#364 fix: Use "should_" test name prefix in more tests
  tests/test_storage_bucket.py
Labels: automerge, bug, python

#365 chore: Bump code coverage percentage to 98(!)
  pyproject.toml
Labels: automerge, python

#366 fix: Show correct badges
  README.md
Labels: automerge, documentation

#368 refactor: Log arguments within argument parser
  backend/check_stac_metadata/task.py
  tests/test_check_stac_metadata_logging.py
Labels: automerge, python

#360 feat: Save STAC validation results to DB
  backend/check_stac_metadata/task.py
  backend/resources.py
  backend/validation_results_model.py
  infrastructure/processing_stack.py
  tests/aws_utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
Labels: automerge, enhancement, python

#374 chore: Update Python packages
  poetry.lock
Labels: automerge, dependencies, python

#373 refactor: api endpoint validation and tests
  backend/api_responses.py
  backend/dataset_versions/entrypoint.py
  backend/datasets/entrypoint.py
  tests/test_api_endpoint_handler.py
  tests/test_dataset_versions_endpoint.py
  tests/test_datasets_endpoint.py
Labels: automerge

#372 refactor: Reuse constants
  backend/import_dataset/task.py
  backend/processing_assets_model.py
Labels: automerge, python

#367 feat: Get Import Status
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  USAGE.md
  backend/dataset_versions/create.py
  backend/import_status/__init__.py
  backend/import_status/entrypoint.py
  backend/import_status/get.py
  backend/resources.py
  infrastructure/api_stack.py
  infrastructure/constructs/lambda_endpoint.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
  response.json
  tests/aws_utils.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
Labels: automerge, python

#376 fix: Use default GitHub merge commit message
  .kodiak.toml
Labels: automerge, bug

#370 refactor: Pull reused code out of tasks
  backend/check_files_checksums/task.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
Labels: automerge, python

#377 refactor: Reuse JSON types
  backend/api_responses.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/dataset_versions/entrypoint.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/entrypoint.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  backend/import_dataset/task.py
  backend/import_status/entrypoint.py
  backend/import_status/get.py
  backend/types.py
  backend/validation_failure/task.py
  backend/validation_summary/task.py
  tests/test_api_endpoint_handler.py
Labels: automerge, python

#371 fix: Run non-infrastructure tests offline
  .github/workflows/test.yml
  backend/check_stac_metadata/utils.py
  backend/datasets/entrypoint.py
  poetry.lock
  pyproject.toml
Labels: automerge, python

#379 chore: Remove duplicate subtest
  tests/test_check_stac_metadata.py
Labels: automerge, python

#384 refactor: Pull out json file object creator
  tests/file_utils.py
  tests/test_check_stac_metadata.py
  tests/test_processing_stack.py
Labels: automerge, python

#385 chore: Update Python packages weekly
  .github/dependabot.yml
Labels: automerge, dependencies, python

#381 refactor: Simplify STAC dataset validator
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
Labels: automerge, python

#386 chore: Update Python packages
  poetry.lock
Labels: automerge, dependencies, python

#388 test: Use subtests for multiple assertions
  tests/test_datasets_endpoint.py
Labels: automerge, python

#390 feat(infra): fixed users role name
  backend/resources.py
  infrastructure/users_stack.py
Labels: automerge

#392 fix: Change dependabot time configuration value to string
  .github/dependabot.yml
  .pre-commit-config.yaml
Labels: automerge, bug

#396 feat: add extra fields to validation table
  backend/check_stac_metadata/utils.py
  backend/validation_results_model.py
  infrastructure/processing_stack.py
  tests/test_check_stac_metadata.py
Labels: automerge

#397 feat: Prep to run tests in parallel
  .github/workflows/test.yml
  pyproject.toml
  tests/aws_utils.py
  tests/conftest.py
  tests/general_generators.py
  tests/test_check_stac_metadata.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_processing_stack.py
Labels: automerge

#402 refactor: Pull out processing asset type enum & more
  backend/check.py
  backend/check_files_checksums/task.py
  backend/check_stac_metadata/utils.py
  backend/processing_assets_model.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
Labels: automerge

#403 fix: Count only assets in content iterator
  backend/content_iterator/task.py
  tests/test_content_iterator.py
Labels: automerge, bug

#404 fix: correct name for validation index attribute
  backend/validation_results_model.py
  infrastructure/processing_stack.py
Labels: automerge

#405 refactor: Rename log key
  backend/dataset_versions/create.py
  backend/import_dataset/task.py
  backend/import_status/get.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_logging.py
Labels: automerge

#409 feat: get import validation status
  app.py
  backend/import_status/get.py
  infrastructure/api_stack.py
  infrastructure/processing_stack.py
  poetry.lock
  pyproject.toml
  tests/aws_utils.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
Labels: automerge

#407 feat: Add script to clear S3 buckets
  clear-s3-buckets.bash
Labels: automerge, enabler story

#401 feat: Implement validation summary task
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  backend/check.py
  backend/check_files_checksums/task.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  backend/validation_results_model.py
  backend/validation_summary/task.py
  infrastructure/processing_stack.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
  tests/internal_generators.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_processing_stack.py
  tests/test_validation_summary.py
Labels: automerge, enhancement

#410 feat: Implement validation summary task logging
  backend/validation_summary/task.py
  tests/test_validation_summary_logging.py
Labels: automerge

#415 chore: Don't install AWS CLI OS package
  .github/workflows/test.yml
Labels: automerge, enabler story

#414 feat: Add pull request template
  .github/pull_request_template.md
Labels: automerge, documentation

#417 refactor: Remove unnecessary f-strings
  backend/datasets/create.py
  backend/datasets/get.py
  backend/datasets/update.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/lambda_endpoint.py
Labels: automerge

#416 refactor: Don't import both core and core.*
  infrastructure/api_stack.py
  infrastructure/constructs/batch_job_queue.py
  infrastructure/constructs/batch_submit_job_task.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/lambda_task.py
  infrastructure/constructs/table.py
  infrastructure/constructs/task_job_definition.py
  infrastructure/networking_stack.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
  infrastructure/users_stack.py
Labels: automerge

#413 fix: Use "assets" property instead of "item_assets"
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
  tests/test_processing_stack.py
Labels: automerge, bug

#420 refactor: Simplify pyproject.toml
  pyproject.toml
Labels: automerge

#419 fix: report correct status of step function when validation fails
  backend/import_status/get.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#425 chore: Update pynamodb
  backend/check_files_checksums/task.py
  backend/check_stac_metadata/utils.py
  backend/dataset_model.py
  backend/datasets/create.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  poetry.lock
  pyproject.toml
  tests/aws_utils.py
  tests/general_generators.py
  tests/test_check_files_checksums_logging.py
Labels: automerge, dependencies, python

#428 feat: Auto generate AWS resource names prep
  app.py
  backend/dataset_versions/create.py
  backend/import_dataset/task.py
  backend/parameter_store.py
  backend/resources.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
  tests/test_check_stac_metadata.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge, enabler story

#432 feat: Log missing parameters
  backend/parameter_store.py
  tests/test_parameter_store.py
Labels: automerge

#433 refactor: Generate storage bucket ARN from name
  backend/import_dataset/task.py
  backend/parameter_store.py
  infrastructure/storage_stack.py
  tests/test_check_stac_metadata.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge

#418 ci: Exclude more files from CDK
  .dockerignore
Labels: automerge

#421 feat: implement validation handling for incorrect staging bucket access
  backend/check.py
  backend/check_files_checksums/task.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
Labels: automerge

#437 fix: Typo in datasets title index name
  backend/dataset_model.py
  backend/datasets/create.py
  backend/datasets/get.py
  backend/datasets/update.py
Labels: automerge

#438 chore: Remove unused enum entry
  backend/resources.py
Labels: automerge

#442 test: Pull out constants
  tests/aws_utils.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
Labels: automerge

#443 fix: give s3 batch copy role correct permissions
  USAGE.md
  app.py
  infrastructure/processing_stack.py
Labels: automerge

#445 test: Add more details if execution output is missing
  tests/test_processing_stack.py
Labels: automerge

#444 refactor: Remove unnecessary nesting
  tests/test_import_dataset.py
  tests/test_processing_stack.py
Labels: automerge

#447 test: Unconditionally delete resources
  tests/test_import_dataset.py
  tests/test_processing_stack.py
Labels: automerge

#448 feat: Add user validation for non S3 URL and multiple directories
  backend/check.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
Labels: automerge

#454 refactor: Simplify import dataset test
  tests/test_import_dataset.py
Labels: automerge

#455 fix: changed dynamodb billing model to pay per request
  infrastructure/constructs/table.py
Labels: automerge

#439 refactor: remove underscores from endpoint names
  backend/resources.py
  infrastructure/api_stack.py
  infrastructure/constructs/lambda_endpoint.py
Labels: automerge

#458 refactor: Strip file prefixes when copying prep
  backend/import_dataset/task.py
  backend/import_status/get.py
  backend/parameter_store.py
  infrastructure/constructs/batch_job_queue.py
  infrastructure/constructs/batch_submit_job_task.py
  infrastructure/constructs/lambda_task.py
  infrastructure/processing_stack.py
  tests/test_import_dataset.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#468 feat: Use latest Poetry installer
  backend/Dockerfile
Labels: automerge

#467 refactor: Strip file prefixes when copying prep 2
  backend/import_dataset/task.py
  backend/import_dataset_file/__init__.py
  backend/import_dataset_file/task.py
  backend/import_dataset_keys.py
  backend/parameter_store.py
  infrastructure/processing_stack.py
  tests/aws_utils.py
  tests/test_import_dataset.py
  tests/test_import_dataset_file_logging.py
Labels: automerge

#459 feat: validate all same directory checks at once
  backend/check_stac_metadata/utils.py
  tests/test_check_files_checksums.py
  tests/test_check_stac_metadata.py
  tests/test_processing_stack.py
Labels: automerge

#471 docs: Add summary of import status end point
  USAGE.md
Labels: automerge

#456 fix: Strip file prefixes when copying
  backend/import_dataset/task.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
Labels: automerge, bug

#472 refactor: Auto-generate AWS resource names prep
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_logging.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_validation_summary.py
Labels: automerge

#474 feat: increase batch array size to maximum amount
  backend/content_iterator/task.py
  tests/aws_utils.py
  tests/test_content_iterator.py
Labels: automerge

#475 refactor: Misc
  USAGE.md
  backend/import_dataset/task.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
Labels: automerge

#476 docs: Cleanup bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge, documentation

#477 feat: Parameterise processing assets table name
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/utils.py
  backend/content_iterator/task.py
  backend/import_dataset/task.py
  backend/parameter_store.py
  backend/processing_assets_model.py
  backend/resources.py
  infrastructure/constructs/parameter.py
  infrastructure/constructs/task_job_definition.py
  infrastructure/processing_stack.py
  tests/aws_utils.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_content_iterator.py
Labels: automerge, enabler story

#479 refactor: Misc
  app.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  backend/datasets_model.py
  infrastructure/api_stack.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
  tests/aws_utils.py
  tests/test_dataset_versions_endpoint_logging.py
Labels: automerge
