Repository linz/geostore, pull requests merged in 2021-01, with the labels that each got.

#160 ci: Add human readable step names
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: automerge

#169 fix: Avoid duplicate codeQL runs
  .github/workflows/codeql-analysis.yml
Labels: automerge

#171 feat: Lint Dockerfiles
  .hadolint.yaml
  .pre-commit-config.yaml
  datalake/backend/processing/check_files_checksums/Dockerfile
  datalake/backend/processing/check_flat_directory_structure/Dockerfile
  datalake/backend/processing/check_stac_metadata/Dockerfile
  ignored:   - DL3000   - SC1010
Labels: automerge

#172 feat: Remove untracked packages when installing
  reset-dev-env.bash
Labels: automerge

#167 feat: Validate flat directory structure
  datalake/backend/processing/check_flat_directory_structure/Dockerfile
  datalake/backend/processing/check_flat_directory_structure/__init__.py
  datalake/backend/processing/check_flat_directory_structure/task.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/utils.py
  datalake/processing_stack.py
Labels: automerge

#170 doc: Create bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge

#118 feat: Introduce mypy
  .gitignore
  .pre-commit-config.yaml
  datalake/backend/processing/check_stac_metadata/__init__.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/processing_stack.py
  poetry.lock
  pyproject.toml
Labels: automerge

#174 feat(infra): add processing assets storage table
  datalake/processing_stack.py
Labels: automerge

#175 style(infra): fix invalid variable name
  datalake/storage_stack.py
Labels: automerge

#177 chore: Remove accidentally added file
  ignored:   - DL3000   - SC1010
Labels: automerge

#181 ci: properly destroy all AWS stacks after testing
  .github/workflows/test.yml
Labels: automerge

#180 ci: use same Node and CDK versions for local development and CI
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: automerge

#187 refactor(infra): rename 'source_stack' to 'staging_stack' (closes #74)
  app.py
  cdk.json
  datalake/backend/tests/test_processing_stack.py
  datalake/staging_stack.py
Labels: automerge

#185 docs: Link to Confluence Azure login page
  README.md
Labels: automerge

#190 ci: Print full test output diff
  .github/workflows/test.yml
Labels: automerge

#193 docs: Add Docker dev env documentation
  README.md
Labels: automerge

#196 docs: Refine CDK docs
  README.md
Labels: automerge

#195 chore: Update Python packages
  poetry.lock
Labels: automerge, dependencies

#199 docs: Avoid AWS Azure login prompt
  README.md
Labels: automerge, enhancement

#192 fix: Remove duplicate shellcheck run
  .github/workflows/test.yml
Labels: automerge

#200 feat: Install ipdb for development
  README.md
  poetry.lock
  pyproject.toml
Labels: automerge, enhancement

#201 chore: Remove unnecessary file
  datalake/backend/processing/check_files_checksums/__init__.py
Labels: automerge

#90 feat: Expand typing support
  .pre-commit-config.yaml
  app.py
  datalake/backend/endpoints/datasets/create.py
  datalake/backend/endpoints/datasets/delete.py
  datalake/backend/endpoints/datasets/entrypoint.py
  datalake/backend/endpoints/datasets/get.py
  datalake/backend/endpoints/datasets/update.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/utils.py
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: automerge

#202 refactor: Reference app.py constants
  app.py
  datalake/backend/tests/test_processing_stack.py
Labels: automerge, enhancement
