Repository linz/geostore, pull requests merged in 2021-05, with the labels that each got.

#648 fix: Use defaults as documented
  backend/clock.py
  backend/datasets_model.py
Labels: automerge

#647 feat: Deploy pull requests labeled "automerge"
  .github/workflows/deploy.yml
Labels: automerge

#653 fix: Run deployment test on automerge pull requests
  .github/workflows/deploy.yml
Labels: automerge

#651 chore: Disable master deploy check
  .github/workflows/deploy.yml
Labels: automerge

#649 refactor: Use implicitly generated dataset ID
  tests/aws_utils.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#656 fix: Match automerge label on any event
  .github/workflows/deploy.yml
Labels: automerge

#657 feat: Make ULID timestamp readable
  backend/datasets_model.py
  poetry.lock
  pyproject.toml
  tests/test_datasets_endpoint.py
Labels: automerge

#650 feat: Add dataset title to S3 key
  app.py
  backend/import_dataset/task.py
  infrastructure/processing_stack.py
  poetry.lock
  pyproject.toml
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_processing_stack.py
Labels: automerge

#659 docs: Fix code review checklist URL
  .github/pull_request_template.md
Labels: automerge, documentation

#658 feat: added read only role for all linz users
  backend/resources.py
  infrastructure/api_stack.py
Labels: automerge

#660 tests: Use constant status codes
  tests/test_dataset_versions_endpoint.py
  tests/test_datasets_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#661 feat: Change dataset version to ULID
  backend/dataset_versions/create.py
  tests/test_dataset_versions_endpoint.py
Labels: automerge

#646 refactor(infra): use nested stacks with cross-stack references passed using parameters
  app.py
  infrastructure/api_stack.py
  infrastructure/lambda_layers_stack.py
  infrastructure/lds.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
Labels: automerge

#664 feat: Track generated CDK context
  .gitignore
  cdk.context.json
Labels: automerge

#665 refactor: Pull out backend directory name
  infrastructure/constructs/backend.py
  infrastructure/constructs/bundled_code.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/task_job_definition.py
Labels: automerge

#666 refactor: modified deploy workflows to deploy to nonprod on merge
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
Labels: automerge

#671 refactor: Avoid unused test arguments
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_import_dataset_logging.py
Labels: automerge

#676 feat: use static name for s3 buckets
  app.py
  backend/datasets/delete.py
  backend/import_dataset/task.py
  backend/parameter_store.py
  backend/resources.py
  infrastructure/api_stack.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
  tests/test_check_stac_metadata.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge

#679 refactor: Type annotate AWS API literals
  backend/import_dataset/task.py
Labels: automerge

#677 refactor: removed kwargs argument from stacks
  infrastructure/api_stack.py
  infrastructure/lambda_layers_stack.py
  infrastructure/lds_stack.py
  infrastructure/networking_stack.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
Labels: automerge

#680 fix: add retain policy to prod and removing from CI
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  README.md
Labels: automerge

#684 refactor: Pull out execution ARN key constant
  backend/api_responses.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/update.py
  backend/import_status/get.py
  backend/step_function_event_keys.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
Labels: automerge

#687 refactor: Simplify parameter access
  infrastructure/api_stack.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/processing_stack.py
Labels: automerge

#690 refactor: Change `LambdaTask` to a `LambdaInvoke` subclass
  infrastructure/constructs/lambda_task.py
  infrastructure/processing_stack.py
Labels: automerge

#695 chore: remove useless docstrings
  infrastructure/api_stack.py
  infrastructure/networking_stack.py
  infrastructure/processing_stack.py
Labels: automerge

#694 refactor(infra): rename S3 and API user roles
  backend/resources.py
  infrastructure/api_stack.py
Labels: automerge

#693 refactor: change API properties names to snake_case
  USAGE.md
  backend/api_responses.py
  backend/dataset_versions/create.py
  backend/error_response_keys.py
  backend/import_dataset_keys.py
  backend/step_function_event_keys.py
  tests/test_api_endpoint_handler.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
Labels: automerge

#691 feat: dataset catalog
  backend/datasets/create.py
  backend/datasets_model.py
  backend/import_dataset/task.py
  backend/pystac_io_methods.py
  infrastructure/api_stack.py
  poetry.lock
  pyproject.toml
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
Labels: automerge

#697 refactor: Change nested stacks into constructs
  app.py
  infrastructure/application_stack.py
  infrastructure/constructs/api.py
  infrastructure/constructs/batch_submit_job_task.py
  infrastructure/constructs/bundled_code.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/common.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/lambda_layers.py
  infrastructure/constructs/lambda_layers/botocore/poetry.lock
  infrastructure/constructs/lambda_layers/botocore/pyproject.toml
  infrastructure/constructs/lds.py
  infrastructure/constructs/processing.py
  infrastructure/constructs/removal_policy.py
  infrastructure/constructs/roles.py
  infrastructure/constructs/runtime.py
  infrastructure/constructs/staging.py
  infrastructure/constructs/storage.py
  infrastructure/constructs/table.py
Labels: automerge

#704 refactor: Pull out API key constants
  backend/api_keys.py
  backend/api_responses.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/utils.py
  backend/content_iterator/task.py
  backend/import_status/get.py
  backend/validation_summary/task.py
  infrastructure/constructs/processing.py
  tests/test_api_endpoint_handler.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_content_iterator.py
  tests/test_dataset_versions_endpoint.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
  tests/test_validation_summary.py
  tests/test_validation_summary_logging.py
Labels: automerge

#705 refactor: Pull out dynamodb key prefix constants
  backend/check_files_checksums/task.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  backend/datasets_model.py
  backend/import_dataset/task.py
  backend/import_status/get.py
  backend/models.py
  backend/validation_results_model.py
  backend/validation_summary/task.py
  tests/aws_utils.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_content_iterator.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#713 refactor: Pull out constants
  backend/check_stac_metadata/utils.py
  backend/datasets/create.py
  backend/datasets/update.py
  backend/import_status/get.py
  backend/stac_format.py
  tests/stac_objects.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#716 refactor: rename product to Geostore
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  CODING.md
  README.md
  USAGE.md
  app.py
  backend/resources.py
  cdk.context.json
  infrastructure/constructs/api.py
  infrastructure/constructs/batch_job_queue.py
  infrastructure/constructs/storage.py
  infrastructure/networking_stack.py
  pyproject.toml
  reset-dev-env.bash
  tests/test_datasets_endpoint.py
  tests/test_processing_stack.py
  tests/test_storage_bucket.py
Labels: automerge

#689 feat: Make copy jobs synchronous
  backend/check_stac_metadata/task.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/import_dataset/task.py
  backend/import_status/get.py
  backend/step_function.py
  backend/step_function_event_keys.py
  backend/upload_status/__init__.py
  backend/upload_status/task.py
  backend/validation_summary/task.py
  infrastructure/constructs/api.py
  infrastructure/constructs/processing.py
  infrastructure/constructs/s3_policy.py
  poetry.lock
  pyproject.toml
  tests/aws_utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_content_iterator.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_processing_stack.py
  tests/test_step_function_logging.py
  tests/test_upload_status.py
  tests/test_upload_status_logging.py
  tests/test_validation_summary.py
  tests/test_validation_summary_logging.py
Labels: automerge

#714 feat: Shorten dataset datetime format
  backend/datasets_model.py
  tests/test_datasets_endpoint.py
Labels: automerge

#720 docs: Fix STAC documentation
  USAGE.md
Labels: automerge, documentation

#723 fix: Correct botocore dependabot path
  .github/dependabot.yml
Labels: automerge, dependencies

#719 feat: Add badges
  README.md
Labels: automerge, documentation

#724 feat: Remove "prod" resource name prefix
  USAGE.md
  backend/resources.py
  infrastructure/constructs/batch_job_queue.py
  infrastructure/constructs/lds.py
  infrastructure/constructs/task_job_definition.py
  infrastructure/networking_stack.py
Labels: automerge, documentation, enhancement

#722 docs: Manage renaming datasets
  USAGE.md
Labels: automerge, documentation

#717 feat: Enable GitHub Actions cache clearing
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  .github/workflows/test.yml
  README.md
Labels: automerge

#729 tests: Prep for 100% coverage
  backend/check_stac_metadata/utils.py
  pyproject.toml
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_parameter_store.py
Labels: automerge

#732 tests: Prep for 100% coverage part deux
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  .github/workflows/test.yml
  README.md
  app.py
  backend/environment.py
  backend/parameter_store.py
  backend/resources.py
  backend/validation_failure/__init__.py
  backend/validation_failure/task.py
  infrastructure/application_stack.py
  infrastructure/constructs/api.py
  infrastructure/constructs/batch_job_queue.py
  infrastructure/constructs/batch_submit_job_task.py
  infrastructure/constructs/import_file_function.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/lambda_layers.py
  infrastructure/constructs/lds.py
  infrastructure/constructs/processing.py
  infrastructure/constructs/storage.py
  infrastructure/constructs/table.py
  infrastructure/constructs/task_job_definition.py
  infrastructure/constructs/version.py
  infrastructure/networking_stack.py
  tests/aws_utils.py
  tests/conftest.py
  tests/general_generators.py
  tests/internal_generators.py
  tests/stac_generators.py
  tests/test_prefix_non_prod_name.py
  tests/test_upload_status.py
Labels: automerge

#733 tests: Prep for 100 percent coverage part trois
  README.md
  backend/import_asset_file/task.py
  backend/import_dataset_file.py
  backend/import_metadata_file/task.py
  pyproject.toml
  tests/test_import_asset_file.py
  tests/test_import_asset_file_logging.py
  tests/test_import_dataset_file.py
  tests/test_import_metadata_file_logging.py
Labels: automerge

#727 feat: root catalog
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  .github/workflows/test.yml
  backend/check_stac_metadata/utils.py
  backend/datasets/create.py
  backend/import_dataset/task.py
  backend/parameter_store.py
  backend/populate_catalog/__init__.py
  backend/populate_catalog/task.py
  backend/pystac_io_methods.py
  backend/s3.py
  backend/stac_format.py
  infrastructure/application_stack.py
  infrastructure/constructs/api.py
  infrastructure/constructs/bundled_code.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/lambda_config.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/lambda_layers.py
  infrastructure/constructs/processing.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
  tests/aws_utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset.py
  tests/test_populate_catalog.py
  tests/test_processing_stack.py
Labels: automerge

#734 tests: 100% coverage
  .github/workflows/test.yml
  .gitignore
  README.md
  backend/check_stac_metadata/task.py
  backend/datasets/entrypoint.py
  backend/datasets/get.py
  backend/datasets_model.py
  backend/import_dataset/task.py
  backend/import_dataset_file.py
  backend/import_metadata_file/task.py
  backend/pystac_io_methods.py
  backend/validation_results_model.py
  pyproject.toml
  tests/aws_utils.py
  tests/test_datasets_endpoint.py
  tests/test_import_asset_file.py
  tests/test_import_dataset_file.py
  tests/test_import_metadata_file.py
Labels: automerge, enabler story

#747 feat: Use latest Prettier release
  .pre-commit-config.yaml
Labels: automerge, enhancement

#745 docs: updated dataset endpoint documentation
  USAGE.md
Labels: automerge

#750 feat: Use most recent Python 3.8 patch version
  .python-version
Labels: automerge

#752 refactor: Pass dataset prefix earlier in pipeline to avoid fetching in multiple places
  backend/check_stac_metadata/task.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/import_dataset/task.py
  backend/step_function.py
  infrastructure/application_stack.py
  infrastructure/constructs/processing.py
  tests/stac_generators.py
  tests/test_content_iterator.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
Labels: automerge

#741 feat: update dataset catalog with version
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/prod-upgrade-deploy-test.yml
  .github/workflows/test.yml
  backend/api_keys.py
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  backend/datasets/create.py
  backend/import_dataset/task.py
  backend/parameter_store.py
  backend/populate_catalog/task.py
  backend/sqs_message_attributes.py
  backend/stac_format.py
  backend/update_dataset_catalog/__init__.py
  backend/update_dataset_catalog/task.py
  infrastructure/constructs/api.py
  infrastructure/constructs/processing.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
  tests/stac_objects.py
  tests/test_check_stac_metadata.py
  tests/test_datasets_endpoint.py
  tests/test_import_dataset_logging.py
  tests/test_populate_catalog.py
  tests/test_processing_stack.py
  tests/test_update_dataset_catalog.py
Labels: automerge
