Repository linz/geostore, pull requests merged in 2021-02, with the labels that each got.

#210 feat: Stricter type validation
  datalake/backend/endpoints/datasets/delete.py
  datalake/backend/endpoints/datasets/model.py
  datalake/backend/processing/content_iterator/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  setup.cfg
Labels: automerge

#203 feat: Improve STAC validation logging
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_check_stac_metadata_logging.py
Labels: automerge, enhancement

#204 feat: Format more languages
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .hadolint.yaml
  .kodiak.toml
  .pre-commit-config.yaml
  .yamllint.yml
  poetry.lock
  pyproject.toml
Labels: automerge, enhancement

#179 feat: Save URL multihashes to DB
  app.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/conftest.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_check_stac_metadata_logging.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/utils.py
  datalake/constructs/batch_submit_job_task.py
  datalake/networking_stack.py
  datalake/processing_stack.py
  poetry.lock
  pyproject.toml
Labels: automerge

#213 ci: set users aws account IDs for deployment
  .github/workflows/deploy.yml
Labels: automerge

#208 feat(infra): user roles stack implementation
  README.md
  app.py
  datalake/api_stack.py
  datalake/users_stack.py
Labels: automerge

#217 fix: Install backend dependencies when running CDK
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: automerge

#198 ci: Allow deployment of multiple stacks
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  README.md
  app.py
  cdk.json
  datalake/api_stack.py
  datalake/backend/endpoints/datasets/model.py
  datalake/backend/endpoints/utils.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_lambda_functions.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/test_storage_bucket.py
  datalake/backend/tests/utils.py
  datalake/constructs/batch_job_queue.py
  datalake/constructs/task_job_definition.py
  datalake/networking_stack.py
  datalake/processing_stack.py
  datalake/staging_stack.py
  datalake/storage_stack.py
Labels: automerge

#218 feat: allow ci stacks to be deployed independently
  .github/workflows/test.yml
  .github/workflows/wait-for-stack-teardown.bash
Labels: automerge

#205 feat: Improve docker lint pre commit hook
  .pre-commit-config.yaml
Labels: automerge

#214 feat: Use PynamoDB built-in model serializer
  datalake/backend/endpoints/datasets/create.py
  datalake/backend/endpoints/datasets/get.py
  datalake/backend/endpoints/datasets/list.py
  datalake/backend/endpoints/datasets/model.py
  datalake/backend/endpoints/datasets/serializer.py
  datalake/backend/endpoints/datasets/update.py
Labels: automerge

#215 Disallow untyped definitions
  app.py
  datalake/api_stack.py
  datalake/backend/endpoints/datasets/create.py
  datalake/backend/endpoints/datasets/delete.py
  datalake/backend/endpoints/datasets/entrypoint.py
  datalake/backend/endpoints/datasets/get.py
  datalake/backend/endpoints/datasets/list.py
  datalake/backend/endpoints/datasets/model.py
  datalake/backend/endpoints/datasets/update.py
  datalake/backend/endpoints/utils.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/processing/content_iterator/task.py
  datalake/backend/processing/validation_failure/task.py
  datalake/backend/processing/validation_summary/task.py
  datalake/backend/tests/conftest.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_check_stac_metadata_logging.py
  datalake/backend/tests/test_datasets_endpoint.py
  datalake/backend/tests/test_lambda_functions.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/test_storage_bucket.py
  datalake/backend/tests/utils.py
  datalake/networking_stack.py
  datalake/staging_stack.py
  datalake/storage_stack.py
  datalake/users_stack.py
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: automerge

#223 feat: Control dev env reset with flags
  reset-dev-env.bash
Labels: automerge

#230 feat: Tweak automerge configuration
  .kodiak.toml
Labels: automerge

#228 fix: Reintroduce removing untracked Python packages
  reset-dev-env.bash
Labels: automerge

#232 fix: Force remove package directories
  reset-dev-env.bash
Labels: automerge, bug

#235 refactor: moved dataset types into utils
  datalake/backend/endpoints/datasets/common.py
  datalake/backend/endpoints/datasets/create.py
  datalake/backend/endpoints/datasets/delete.py
  datalake/backend/endpoints/datasets/get.py
  datalake/backend/endpoints/datasets/update.py
  datalake/backend/endpoints/utils.py
  datalake/backend/tests/test_datasets_endpoint.py
  datalake/backend/tests/utils.py
Labels: automerge

#236 refactor: change test to call main instead of state machine
  datalake/backend/tests/test_check_stac_metadata.py
Labels: automerge

#222 chore: Update Python packages
  poetry.lock
  pyproject.toml
Labels: automerge

#234 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enabler_story.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: automerge

#224 feat: Launch dataset import
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  app.py
  datalake/api_stack.py
  datalake/backend/endpoints/dataset_versions/__init__.py
  datalake/backend/endpoints/dataset_versions/create.py
  datalake/backend/endpoints/dataset_versions/entrypoint.py
  datalake/backend/endpoints/datasets/create.py
  datalake/backend/endpoints/datasets/delete.py
  datalake/backend/endpoints/datasets/get.py
  datalake/backend/endpoints/datasets/list.py
  datalake/backend/endpoints/datasets/update.py
  datalake/backend/endpoints/model.py
  datalake/backend/endpoints/utils.py
  datalake/backend/tests/conftest.py
  datalake/backend/tests/test_dataset_versions_endpoint.py
  datalake/backend/tests/test_dataset_versions_endpoint_logging.py
  datalake/backend/tests/test_lambda_functions.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/utils.py
  datalake/processing_stack.py
  datalake/storage_stack.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
Labels: automerge

#237 feat: Enable dependabot third party package scanning
  .github/dependabot.yml
Labels: automerge

#241 refactor: Use `hex` property of UUID objects
  datalake/backend/endpoints/dataset_versions/create.py
  datalake/backend/tests/utils.py
Labels: automerge

#243 fix: fixed a typo in deploy package extras
  .github/workflows/deploy.yml
Labels: automerge

#248 fix: Upgrade AWS CDK package
  datalake/constructs/batch_job_queue.py
  datalake/constructs/lambda_task.py
  datalake/processing_stack.py
  poetry.lock
  pyproject.toml
Labels: automerge, dependencies

#249 Simplify extras names
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  datalake/backend/bundle.bash
  datalake/backend/processing/check_stac_metadata/Dockerfile
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
Labels: automerge, dependencies

#251 feat: Clean out Git cruft as part of dev setup
  reset-dev-env.bash
Labels: automerge, enhancement

#250 Improve bundling error handling
  datalake/backend/bundle.bash
Labels: automerge

#256 Improve bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge

#259 feat: Remove cdk.out as part of dev env reset
  reset-dev-env.bash
Labels: automerge, enhancement

#261 feat: updated poetry packages
  poetry.lock
Labels: automerge, dependencies

#262 test: Rename tests for clarity
  datalake/backend/tests/test_check_stac_metadata_logging.py
Labels: automerge

#252 chore: Use actual booleans in cdk.json
  cdk.json
Labels: automerge, enhancement

#264 refactor: Remove dependency on `unittest.TestCase`
  datalake/backend/tests/test_check_stac_metadata_logging.py
  datalake/backend/tests/test_dataset_versions_endpoint_logging.py
Labels: automerge

#266 docs: Expand package update process
  README.md
Labels: automerge, documentation

#267 feat: Set log level to debug across state machine
  datalake/common.py
  datalake/constructs/batch_submit_job_task.py
  datalake/constructs/bundled_lambda_function.py
Labels: automerge

#265 chore: Remove unused exception classes
  datalake/backend/tests/test_processing_stack.py
Labels: automerge

#263 refactor: De-duplicate test constants
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/utils.py
Labels: automerge

#268 feat: Don't remove IDEA configuration
  reset-dev-env.bash
Labels: automerge

#294 fix: Verify flat structure for assets
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/tests/test_check_stac_metadata.py
Labels: automerge, bug

#285 fix: Don't exit when specifying `--delete`
  reset-dev-env.bash
Labels: automerge, bug

#287 chore: Update Python packages
  datalake/api_stack.py
  datalake/constructs/batch_job_queue.py
  datalake/constructs/batch_submit_job_task.py
  datalake/constructs/table.py
  datalake/constructs/task_job_definition.py
  datalake/networking_stack.py
  datalake/processing_stack.py
  datalake/staging_stack.py
  datalake/storage_stack.py
  datalake/users_stack.py
  poetry.lock
Labels: automerge, dependencies

#296 feat: Copy fewer files when creating CDK Docker assets
  .dockerignore
Labels: automerge, enabler story

#64 feat: Validate checksum
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  datalake/backend/processing/Dockerfile
  datalake/backend/processing/assets_model.py
  datalake/backend/processing/check_files_checksums/Dockerfile
  datalake/backend/processing/check_files_checksums/__init__.py
  datalake/backend/processing/check_files_checksums/task.py
  datalake/backend/processing/check_stac_metadata/task.py
  datalake/backend/processing/content_iterator/task.py
  datalake/backend/tests/test_check_files_checksums.py
  datalake/backend/tests/test_check_files_checksums_logging.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_check_stac_metadata_logging.py
  datalake/backend/tests/test_content_iterator.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/utils.py
  datalake/constructs/batch_submit_job_task.py
  datalake/constructs/bundled_lambda_function.py
  datalake/constructs/lambda_task.py
  datalake/constructs/task_job_definition.py
  datalake/processing_stack.py
  poetry.lock
  pyproject.toml
  reset-dev-env.bash
Labels: enhancement

#300 test: Enable running tests without setting DEPLOY_ENV
  datalake/backend/endpoints/utils.py
  datalake/backend/processing/assets_model.py
Labels: automerge, python

#176 style: check for invalid names in Python
  .pylintrc
  datalake/backend/endpoints/dataset_versions/create.py
  datalake/backend/endpoints/dataset_versions/entrypoint.py
  datalake/backend/endpoints/datasets/create.py
  datalake/backend/endpoints/datasets/delete.py
  datalake/backend/endpoints/datasets/entrypoint.py
  datalake/backend/endpoints/datasets/get.py
  datalake/backend/endpoints/datasets/list.py
  datalake/backend/endpoints/datasets/update.py
  datalake/backend/endpoints/utils.py
  datalake/backend/processing/content_iterator/task.py
  datalake/backend/processing/validation_failure/task.py
  datalake/backend/processing/validation_summary/task.py
  datalake/backend/tests/utils.py
Labels: automerge

#307 feat: Use non-root user in Docker
  datalake/backend/processing/Dockerfile
Labels: automerge, security

#278 feat: Dynamic batch job array size
  datalake/backend/processing/check_files_checksums/task.py
  datalake/backend/processing/content_iterator/task.py
  datalake/backend/tests/test_check_files_checksums.py
  datalake/backend/tests/test_check_files_checksums_logging.py
  datalake/backend/tests/test_check_stac_metadata.py
  datalake/backend/tests/test_content_iterator.py
  datalake/backend/tests/test_processing_stack.py
  datalake/backend/tests/utils.py
  datalake/processing_stack.py
Labels: automerge

#305 test: Fix test name
  datalake/backend/tests/test_check_files_checksums.py
Labels: automerge
