Repository linz/geostore, pull requests merged in 2021-04, with the labels that each got.

#483 feat: Parameterise datasets table name
  app.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  backend/datasets_model.py
  backend/parameter_store.py
  backend/resources.py
  infrastructure/api_stack.py
  infrastructure/storage_stack.py
  tests/aws_utils.py
  tests/test_dataset_versions_endpoint_logging.py
Labels: automerge

#485 feat: Parameterise validation results table name
  app.py
  backend/import_status/get.py
  backend/parameter_store.py
  backend/resources.py
  backend/validation_results_model.py
  backend/validation_summary/task.py
  infrastructure/api_stack.py
  infrastructure/common.py
  infrastructure/constructs/parameter.py
  infrastructure/constructs/table.py
  infrastructure/processing_stack.py
  infrastructure/storage_stack.py
  tests/aws_utils.py
  tests/test_check_stac_metadata.py
  tests/test_validation_summary.py
  tests/test_validation_summary_logging.py
Labels: automerge

#424 feat: Auto generate AWS resource names
  infrastructure/constructs/table.py
Labels: automerge

#486 feat: Modify STAC URLs during copy
  USAGE.md
  backend/import_asset_file/__init__.py
  backend/import_asset_file/task.py
  backend/import_dataset/task.py
  backend/import_file_batch_job_id_keys.py
  backend/import_metadata_file/__init__.py
  backend/import_metadata_file/task.py
  backend/import_status/get.py
  backend/parameter_store.py
  infrastructure/constructs/import_file_function.py
  infrastructure/processing_stack.py
  tests/aws_utils.py
  tests/test_import_asset_file_logging.py
  tests/test_import_dataset.py
  tests/test_import_metadata_file_logging.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#499 refactor: Remove smart-open dev dependency
  poetry.lock
  pyproject.toml
Labels: automerge, dependencies

#497 feat: Allow relative paths in metadata
  USAGE.md
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
Labels: automerge

#500 chore: Use latest aws-azure-login version
  package.json
Labels: automerge, dependencies

#506 docs: Comment out entire sections in PR template by default
  .github/pull_request_template.md
Labels: automerge, documentation, enabler story

#509 chore: Update aws-azure-login package
  package-lock.json
Labels: automerge, dependencies, security

#511 feat: Report duplicate JSON object names
  backend/check.py
  backend/check_stac_metadata/utils.py
  tests/aws_utils.py
  tests/test_check_stac_metadata.py
Labels: automerge

#512 chore: Remove unused enum value
  backend/check.py
Labels: automerge

#514 feat: Report invalid json
  backend/check.py
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
Labels: automerge

#513 refactor: Modified stac validation task to not crash pipeline
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_check_stac_metadata_utils_logging.py
Labels: automerge

#519 refactor: Use key variables for common step function and error strings
  backend/check_files_checksums/utils.py
  backend/content_iterator/task.py
  backend/dataset_versions/create.py
  backend/error_response_keys.py
  backend/import_dataset/task.py
  backend/import_status/get.py
  backend/parameter_store.py
  backend/step_function_event_keys.py
  backend/validation_summary/task.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_content_iterator.py
  tests/test_dataset_versions_endpoint_logging.py
  tests/test_import_dataset.py
  tests/test_import_dataset_logging.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
  tests/test_parameter_store.py
  tests/test_validation_summary.py
  tests/test_validation_summary_logging.py
Labels: automerge

#523 feat: Remove owning group dataset parameter
  USAGE.md
  backend/datasets/create.py
  backend/datasets/get.py
  backend/datasets/update.py
  backend/datasets_model.py
  infrastructure/storage_stack.py
  pyproject.toml
  tests/aws_utils.py
  tests/stac_generators.py
  tests/test_datasets_endpoint.py
Labels: automerge

#536 refactor: Use constants for HTTP response codes
  backend/api_responses.py
  backend/dataset_versions/create.py
  backend/datasets/create.py
  backend/datasets/delete.py
  backend/datasets/get.py
  backend/datasets/list.py
  backend/datasets/update.py
  backend/import_status/get.py
  tests/test_api_endpoint_handler.py
  tests/test_dataset_versions_endpoint.py
  tests/test_datasets_endpoint.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#532 fix: Use new checksum property name
  backend/check_stac_metadata/utils.py
  tests/stac_objects.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_utils_logging.py
  tests/test_import_dataset.py
  tests/test_processing_stack.py
Labels: automerge

#537 refactor: Merge users stack into API stack
  app.py
  infrastructure/api_stack.py
  infrastructure/users_stack.py
Labels: automerge

#524 docs: Simplify usage
  USAGE.md
  backend/resources.py
  infrastructure/constructs/lambda_endpoint.py
  tests/test_datasets_endpoint.py
  tests/test_processing_stack.py
Labels: automerge, documentation

#535 refactor: Check STAC metadata cleanup
  backend/check_stac_metadata/stac_validators.py
  tests/stac_objects.py
  tests/test_check_stac_metadata.py
Labels: automerge

#540 refactor: Make import status messages more meaningful prep
  backend/import_status/get.py
  tests/aws_utils.py
  tests/test_import_status_endpoint.py
  tests/test_import_status_logging.py
Labels: automerge

#541 feat: Make import status messages more meaningful
  backend/import_status/get.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#547 feat: Run CodeQL on non-master branches only on pull request event
  .github/workflows/codeql-analysis.yml
Labels: automerge

#538 feat: Only allow deleting empty dataset
  backend/datasets/delete.py
  tests/test_datasets_endpoint.py
Labels: automerge

#548 fix: Run CodeQL analysis on optional Python dependencies
  .github/workflows/codeql-analysis.yml
Labels: automerge, dependencies

#551 chore: Unlock AWS ECS package version
  poetry.lock
  pyproject.toml
Labels: automerge

#521 refactor: change check stac metadata to non batch task
  backend/bundle.bash
  backend/check_stac_metadata/task.py
  backend/check_stac_metadata/utils.py
  infrastructure/constructs/lambda_task.py
  infrastructure/processing_stack.py
  tests/test_check_stac_metadata.py
  tests/test_check_stac_metadata_task_logging.py
  tests/test_check_stac_metadata_utils_logging.py
Labels: automerge

#565 chore: Cache pip downloads during bundling
  backend/bundle.bash
Labels: automerge, dependencies

#577 refactor: ignore hadolint issue
  backend/Dockerfile
Labels: automerge

#566 fix: Add Mitchell Paff to authors list
  pyproject.toml
Labels: automerge

#568 feat: Install wheel package during bundling
  backend/bundle.bash
Labels: automerge

#571 fix: bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge

#582 fix: Lock hadolint version
  .pre-commit-config.yaml
Labels: automerge

#583 fix: Grant access to parameter needed for dataset deletion
  app.py
  infrastructure/api_stack.py
  tests/test_datasets_endpoint.py
Labels: automerge

#585 refactor: Move validation results table to storage stack
  app.py
  infrastructure/processing_stack.py
  infrastructure/storage_stack.py
Labels: automerge

#584 refactor: Demote fields to variables
  infrastructure/networking_stack.py
  infrastructure/processing_stack.py
Labels: automerge

#569 fix: ssm throttling issues
  backend/check_files_checksums/task.py
  backend/check_files_checksums/utils.py
  backend/check_stac_metadata/task.py
  backend/content_iterator/task.py
  backend/processing_assets_model.py
  backend/validation_results_model.py
  infrastructure/processing_stack.py
  tests/aws_utils.py
  tests/test_check_files_checksums.py
  tests/test_check_files_checksums_logging.py
  tests/test_check_stac_metadata.py
  tests/test_content_iterator.py
Labels: automerge

#579 refactor: Add botocore Lambda layer
  .github/dependabot.yml
  app.py
  backend/bundle.bash
  infrastructure/api_stack.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/import_file_function.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/lambda_task.py
  infrastructure/lambda_layers/botocore/poetry.lock
  infrastructure/lambda_layers/botocore/pyproject.toml
  infrastructure/lambda_layers_stack.py
  infrastructure/processing_stack.py
  poetry.lock
  pyproject.toml
Labels: automerge, dependencies

#587 fix: Set validation failed if there are errors
  backend/import_status/get.py
  tests/test_import_status_endpoint.py
  tests/test_processing_stack.py
Labels: automerge

#597 chore: Update license date
  LICENSE
Labels: automerge

#596 feat: Reintroduce YAML formatter
  .github/workflows/deploy.yml
  .pre-commit-config.yaml
Labels: automerge

#598 feat: Update license date automatically
  .github/workflows/update-license-year.yml
Labels: automerge

#599 docs: Document vulnerability notification setup
  README.md
Labels: automerge, documentation

#612 fix: Scan Dockerfile in backend directory
  .github/dependabot.yml
Labels: automerge

#603 feat: Use prettier to format files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enabler_story.md
  .github/ISSUE_TEMPLATE/user_story.md
  .github/codeql/codeql-config.yml
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .github/workflows/update-license-year.yml
  .hadolint.yaml
  .pre-commit-config.yaml
  CODING.md
  README.md
  USAGE.md
  package.json
Labels: automerge

#620 refactor: recursive application layer tagging by stack membership
  infrastructure/api_stack.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/import_file_function.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/constructs/lambda_task.py
  infrastructure/constructs/table.py
  infrastructure/networking_stack.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
Labels: automerge

#608 refactor: De-duplicate bundled Lambda code generation
  infrastructure/constructs/bundled_code.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/lambda_endpoint.py
Labels: automerge

#613 refactor: Pull out Python runtimes
  infrastructure/constructs/bundled_code.py
  infrastructure/constructs/bundled_lambda_function.py
  infrastructure/constructs/lambda_endpoint.py
  infrastructure/lambda_layers_stack.py
  infrastructure/runtime.py
Labels: automerge

#617 feat: Add Koordinates storage access role
  README.md
  app.py
  cdk.json
  infrastructure/api_stack.py
  infrastructure/lds.py
  infrastructure/roles.py
Labels: automerge

#631 refactor: Remove default null values
  backend/datasets_model.py
Labels: automerge

#632 fix: Generate unique IDs per dataset
  backend/datasets_model.py
  tests/test_datasets_model_base.py
Labels: automerge

#634 chore: Remove redundant role name suffix
  infrastructure/lds.py
Labels: automerge

#635 feat: Use ULIDs for dataset IDs
  backend/datasets_model.py
  poetry.lock
  pyproject.toml
  tests/test_datasets_endpoint.py
Labels: automerge

#636 feat: Enforce dataset title pattern
  backend/datasets/create.py
  tests/stac_generators.py
  tests/test_datasets_endpoint.py
Labels: automerge

#639 refactor: Nest stacks prep
  app.py
  infrastructure/api_stack.py
  infrastructure/constructs/lambda_task.py
  infrastructure/constructs/table.py
  infrastructure/lambda_layers_stack.py
  infrastructure/lds.py
  infrastructure/processing_stack.py
  infrastructure/staging_stack.py
  infrastructure/storage_stack.py
Labels: automerge
